// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD60O5taMwMkyW4Nh77nypkN4-H3OQ1Oqo',
    appId: '1:338962459051:web:f380135a1d4935b82bcaee',
    messagingSenderId: '338962459051',
    projectId: 'fir-auth-f9438',
    authDomain: 'fir-auth-f9438.firebaseapp.com',
    storageBucket: 'fir-auth-f9438.firebasestorage.app',
    measurementId: 'G-989QJTPY80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf4HvXArkIG36jjaUNNrrwu40l4x0Gm0Y',
    appId: '1:338962459051:android:342a612e7adbd1382bcaee',
    messagingSenderId: '338962459051',
    projectId: 'fir-auth-f9438',
    storageBucket: 'fir-auth-f9438.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCPA3jIb5FY0TvM1CCxt2VARUvULmwfns',
    appId: '1:338962459051:ios:e33c82d7c2fa3ce82bcaee',
    messagingSenderId: '338962459051',
    projectId: 'fir-auth-f9438',
    storageBucket: 'fir-auth-f9438.firebasestorage.app',
    iosBundleId: 'com.obsolete.firebaseAuth',
  );
}
